# Generated by Django 4.1.4 on 2023-03-26 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('order', models.IntegerField(verbose_name='Order')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='Description')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('dueDate', models.DateField(blank=True, null=True, verbose_name='DueDate')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Cover')),
                ('order', models.IntegerField(verbose_name='Order')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.column')),
            ],
        ),
    ]
