# Generated by Django 4.1.4 on 2023-03-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='colType',
            field=models.CharField(choices=[('A', 'Archive'), ('B', 'Backlog'), ('N', 'Normal')], default='N', max_length=1, verbose_name='Type'),
        ),
    ]
