# Generated by Django 4.1.4 on 2023-05-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_card_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='card_covers', verbose_name='Cover'),
        ),
    ]
