# Generated by Django 4.1.4 on 2022-12-23 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('description', models.CharField(max_length=240, verbose_name='Description')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(auto_created=True, verbose_name='Order')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('done', models.BooleanField(verbose_name='Done')),
                ('checklistId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.checklist')),
            ],
        ),
    ]
