name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the frontend Docker image
      run: docker build . --file frontend/Dockerfile --tag ccarb/frontend:$(date +%s)
    - name: Build the backend Docker image
      run: docker build . --file backend/Dockerfile --tag ccarb/backend:$(date +%s)
